### ISSUE TITLE
AssertionError | The module torch.distributed.launch is deprecated and will be removed in future. 

### ISSUE THREAD

**Issue by LiuxinYLX** [bozeklab/worm-swin#1]
My command:

tools/dist_test.sh configs/config_wormswin_mmdetection.py ../Documents/Stage/worm-swin-main/synthetic_csb-1_epoch_36.pth 0 --eval bbox segm  --out outputs/resultat.pkl

My errors:
/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 230, in launch_agent
    spec = WorkerSpec(
  File "<string>", line 14, in __init__
  File "/home/liuxinyang/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 94, in __post_init__
    assert self.local_world_size > 0
AssertionError

My objective: I want to test my own photos but it doesn't work. I also tried :
torchrun --standalone --nnodes=1 --nproc_per_node=1 tools/test.py configs/config_wormswin_mmdetection.py ../Documents/Stage/worm-swin-main/synthetic_csb-1_epoch_36.pth --eval bbox segm --out outputs/resultat.pkl

But it doesn't work either. :( Could you help me, please? TT

**Comment by bossardl** [comment]
Hey, 
In dist_test.sh, replace  **torch.distributed.launch** by **torchrun**. This fixes this issue.

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python -m **torch.distributed.launch** \
    --nnodes=$NNODES \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --nproc_per_node=$GPUS \
    --master_port=$PORT \
    $(dirname "$0")/test.py \
    $CONFIG \
    $CHECKPOINT \
    --launcher pytorch \
    ${@:4}

by :

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
**torchrun** \
    --nnodes=$NNODES \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --nproc_per_node=$GPUS \
    --master_port=$PORT \
    $(dirname "$0")/test.py \
    $CONFIG \
    $CHECKPOINT \
    --launcher pytorch \
    ${@:4}
